language: python
install:
  - pip install git+https://github.com/Psycojoker/baron.git
  - pip install pytest
  - python setup.py install
python:
  - "2.6"
  - "2.7"
  - "3.5"
script:
  - py.test tests
  - bash ./test_doc.sh
notifications:
  irc: "chat.freenode.net#baron"
