language: python
install:
  - pip install git+https://github.com/Psycojoker/baron.git
  - pip install pytest
  - python setup.py install
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
script:
  - py.test tests
notifications:
  irc: "chat.freenode.net#baron"
